# Generated by Django 3.1.7 on 2021-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
