# Generated by Django 3.1.7 on 2021-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_candidate_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achievements',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
