# Generated by Django 3.1.7 on 2021-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sign',
            field=models.ImageField(default=2, upload_to='images/', verbose_name='Sign Pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
