# Generated by Django 3.1.7 on 2021-04-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
