# Generated by Django 3.1.7 on 2021-04-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_extuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extuser',
            old_name='enroll',
            new_name='EnrollmentNumber',
        ),
    ]
