# Generated by Django 3.1.7 on 2021-04-28 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0012_auto_20210427_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extuser',
            new_name='Profile',
        ),
    ]
