# Generated by Django 3.1.7 on 2021-05-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20210428_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='about',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
