# Generated by Django 3.1.7 on 2021-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20210531_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
